polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailsView.as_view(), name='details'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/votes/', views.votes, name='votes'),
]

tut/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    publisher_name = models.CharField(max_length=60)
    question_text = models.CharField(max_length=140)
    publish_date = models.DateTimeField("Date published")

    def recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.publish_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=256)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_five"

    def get_queryset(self):
        return Question.objects.filter(publish_date__lte=timezone.now()).order_by("-publish_date")[:5]


class DetailsView(generic.DetailView):
    model = Question
    template_name = "polls/details.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(publish_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    context_object_name = "q"
    template_name = "polls/results.html"


def votes(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        choice = q.choice_set.get(pk=request.POST['choice'])
    except (KeyError, choice.DoesNotExist):
        raise Http404("You didn't select a choice!")
    else:
        choice.votes += 1
        choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(q.id,)))

polls/templates/polls/details.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<p>Publisher name: <b><a>{{ question.publisher_name }}</a></b></p>
<p>Published on: {{question.publish_date}}</p>
<h1>{{ question.question_text }}</h1>
<form action="{% url 'polls:votes' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all  %}
<input type="radio" name="choice" id="choice{{choice.id}}" value="{{choice.id}}">
<label for="choice{{choice.id}}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}">Home</a>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% if latest_five %}
<ul>
    {% for question in latest_five %}
    <li><a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>There are no recently polls, Come back later</p>
{% endif %}
<a href="{% url 'polls:index' %}">Home</a>

polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<h1>Q: {{q.question_text}}</h1>
<h3>Your votes were:</h3>
<ul>
{% for choice in q.choice_set.all  %}
    <li>{{choice.choice_text}} ({{choice.votes}}) </li>
{% endfor %}
</ul>
<a href="{% url 'polls:index' %}">Home</a>